apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-env-ddtag
  labels:
    dd_tags: "opa"
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: DD_TAGS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['dd_tags']