apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-env-ddtag
spec:
  template:
    spec:
      containers:
        - name: nginx
          env:
            - name: DD_TAGS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['dd_tags']