apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx 
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      serviceAccountName: nginx 
      automountServiceAccountToken: false
      containers:
        - name: nginx
          image: lipenodias/nginx-sre:latest 
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: DD_TAGS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['dd_tags']
          volumeMounts:
            - name: logs
              mountPath: /var/lib/nginx/logs/
            - name: tmp 
              mountPath: /var/lib/nginx/tmp/
            - name: run
              mountPath: /run/nginx/ 
          ports:
            - containerPort: 8080
              protocol: TCP
              name: nginx
            - containerPort: 8081
              protocol: TCP
              name: healthcheck
          resources:
            limits:
              cpu: 250m
              memory: 250Mi
            requests:
              cpu: 150m
              memory: 150Mi
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      enableServiceLinks: false
      terminationGracePeriodSeconds: 40
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      volumes:
        - name: logs
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: run 
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600